Repository acmpesuecc/weatherly, pull requests merged in 2020-10, with the labels that each got.

#8 Added Navbar
  src/components/Navbar.js
Labels: bounty-40, hacktoberfest-accepted

#10 Cd workflow
  .github/workflows/main.yml
  public/favicon_io.zip
  public/weatherlylogo192.png
  public/weatherlylogo512.png
Labels: bounty-100, hacktoberfest-accepted

#11 Designed logo
  public/weatherLogo512.png
  public/weatherly.ico
  public/weatherlyLogo192.png
Labels: bounty-100, hacktoberfest-accepted

#15 Add @material-ui/core package as a dependency
  package.json
Labels: bounty-5, hacktoberfest-accepted

#16 Move logo designs into own folder
  public/logoDesigns/weatherLogo512.png
  public/logoDesigns/weatherlyLogo192.png
  public/logoDesigns/weatherlylogo192.png
  public/logoDesigns/weatherlylogo512.png
Labels: bounty-5, hacktoberfest-accepted

#22 feat: Add API call to fetch weather data from https://openweathermap.org/
  package.json
  src/api/Weather.js
Labels: hacktoberfest-accepted

#23 Added fetch time api
  src/api/Time.js
Labels: hacktoberfest-accepted

#24 Bug fixes
  .github/workflows/main.yml
  src/App.css
  src/components/Navbar.js
Labels: hacktoberfest-accepted
